fastlane_version "1.47.0"

default_platform :ios

platform :ios do

  before_all do
    # ensure_git_status_clean
  end

  desc "Run all the tests"
  lane :test do
    scan(device: "iPhone 6s (9.2)")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "FastLane Example") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end
end
